# Generated by Django 5.0.3 on 2025-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
