# Generated by Django 5.2.12 on 2026-09-09 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwd_forget',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Réinitialisation mot de passe'), ('activation', 'Activation compte'), ('google_link', 'Liaison compte Google')], db_index=True, default='password_reset', max_length=32),
        ),
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Identifiant Google')),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identite Google',
                'verbose_name_plural': 'Identites Google',
                'ordering': ['-created_at'],
            },
        ),
    ]
