# Generated by Django 6.0.3 on 2026-09-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0002_alter_pwd_forget_purpose_googleidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='localentrepot',
            name='contact',
            field=models.CharField(blank=True, help_text='Numéro de téléphone de l’agence (optionnel)', max_length=30, null=True, verbose_name='Contact'),
        ),
    ]
