# Generated by Django 5.2.12 on 2026-09-24 00:14

from django.db import migrations, models


def seed_pdv_koumassi(apps, schema_editor):
    """Reprend l'ancien PDV global « Caisse Koumassi » sur la localité homonyme."""
    LocalEntrepot = apps.get_model('Userauths', 'LocalEntrepot')
    LocalEntrepot.objects.filter(
        fne_point_de_vente='',
        nom__icontains='koumassi',
    ).update(fne_point_de_vente='Caisse Koumassi')


def unseed_pdv_koumassi(apps, schema_editor):
    LocalEntrepot = apps.get_model('Userauths', 'LocalEntrepot')
    LocalEntrepot.objects.filter(fne_point_de_vente='Caisse Koumassi').update(
        fne_point_de_vente='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0003_localentrepot_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='localentrepot',
            name='fne_point_de_vente',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    'Nom exact du point de vente dans l’espace FNE '
                    '(ex. « Caisse Koumassi »). Obligatoire pour certifier '
                    'les ventes de cette localité.'
                ),
                max_length=150,
                verbose_name='Point de vente FNE',
            ),
        ),
        migrations.RunPython(seed_pdv_koumassi, unseed_pdv_koumassi),
    ]
