# Generated by Django 5.0.3 on 2025-12-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0003_alter_customuser_genre_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='customuser_permissions', to='auth.permission'),
        ),
    ]
