# Generated by Django 5.2.12 on 2026-09-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0004_localentrepot_fne_point_de_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plafond_remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant max de remise (Fcfa) pour un agent Accueil. Doit être ≤ au plafond de sa localité. Augmentez-le si l’agent doit accorder une remise plus élevée.', max_digits=12, verbose_name='Plafond de remise'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='plafond_remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant max de remise (Fcfa) pour un agent Accueil. Doit être ≤ au plafond de sa localité. Augmentez-le si l’agent doit accorder une remise plus élevée.', max_digits=12, verbose_name='Plafond de remise'),
        ),
        migrations.AddField(
            model_name='localentrepot',
            name='plafond_remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum de remise (Fcfa) pour cette localité. Les plafonds des agents Accueil ne peuvent pas le dépasser.', max_digits=12, verbose_name='Plafond de remise'),
        ),
    ]
