# Generated by Django 5.0.3 on 2025-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0004_alter_customuser_user_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission'),
        ),
    ]
