# Generated by Django 5.2.7 on 2026-03-04 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0005_alter_customuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocaliteUser',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='caissier', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='role',
            field=models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='caissier', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='localiteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localiteusers', to='Userauths.localiteuser'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='localiteuser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.localiteuser'),
        ),
    ]
