# Generated by Django 5.2.12 on 2026-09-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0005_plafond_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_session_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Session web exclusive ; une nouvelle connexion déconnecte l’ancienne.', max_length=40, verbose_name='Session active'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='active_session_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Session web exclusive ; une nouvelle connexion déconnecte l’ancienne.', max_length=40, verbose_name='Session active'),
        ),
    ]
