# Generated by Django 5.2.7 on 2026-03-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0006_localiteuser_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocaliteUser',
            new_name='SiteUser',
        ),
        migrations.RenameField(
            model_name='historicalcustomuser',
            old_name='localiteuser',
            new_name='siteuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='localiteuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='siteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siteusers', to='Userauths.siteuser'),
        ),
    ]
