# Generated by Django 5.2.7 on 2026-03-05 00:02

import Userauths.models
import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0007_rename_localiteuser_siteuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProfilUser',
            fields=[
                ('pid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('photo', models.TextField(blank=True, default='profils/default/avatar.png', max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_employe', shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, db_index=True, length=8, max_length=20, null=True, prefix='EMP-')),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Profil Utilisateur',
                'verbose_name_plural': 'historical Profils Utilisateurs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProfilUser',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default='profils/default/avatar.png', null=True, upload_to=Userauths.models.profil_image_upload_path)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_employe', shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, length=8, max_length=20, null=True, prefix='EMP-', unique=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
