# Generated by Django 5.2.12 on 2026-03-18 20:34

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0008_historicalprofiluser_profiluser'),
        ('stock', '0015_add_statut_commande'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUser',
            new_name='LocalEntrepot',
        ),
        migrations.RenameField(
            model_name='historicalcustomuser',
            old_name='siteuser',
            new_name='local_entrepot',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='siteuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='local_entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_entrepot_users', to='Userauths.localentrepot'),
        ),
        migrations.AlterField(
            model_name='historicalprofiluser',
            name='numero_employe',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, db_index=True, length=8, max_length=20, null=True, prefix='EMP&B-'),
        ),
        migrations.AlterField(
            model_name='profiluser',
            name='numero_employe',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, length=8, max_length=20, null=True, prefix='EMP&B-', unique=True),
        ),
    ]
