# Generated by Django 6.0.3 on 2026-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0011_alter_customuser_role_chefagence'),
    ]

    operations = [
        migrations.AddField(
            model_name='localentrepot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS (ex: 5.345317 pour Abidjan-Plateau)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='localentrepot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS (ex: -4.024429 pour Abidjan-Plateau)', max_digits=9, null=True),
        ),
    ]
