# Generated by Django 5.2.12 on 2026-05-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0012_localentrepot_latitude_localentrepot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localentrepot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude GPS (ex: 5.345317 pour Abidjan-Plateau)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='localentrepot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude GPS (ex: -4.024429 pour Abidjan-Plateau)', max_digits=9, null=True),
        ),
    ]
