# Generated by Django 5.2.12 on 2026-07-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0014_entreprise_plan_alter_customuser_role_and_more'),
        ('stock', '0040_remove_entreprise_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='localentrepot',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='entreprise',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('chefagence', 'Chef agence'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='caissier', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='role',
            field=models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('chefagence', 'Chef agence'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='caissier', max_length=20),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
    ]
