# Generated by Django 5.2.12 on 2026-07-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0015_remove_entreprise_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('chefagence', 'Chef agence'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur'), ('client', 'Client')], default='caissier', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='role',
            field=models.CharField(choices=[('accueil', 'Service Accueil'), ('caissier', 'Caissier(ère)'), ('livreur', 'Livreur(euse)'), ('chefagence', 'Chef agence'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur'), ('client', 'Client')], default='caissier', max_length=20),
        ),
    ]
