# Generated by Django 6.0.3 on 2026-07-13 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0016_add_client_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('local_entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='Userauths.localentrepot')),
            ],
            options={
                'verbose_name': 'Créneau de disponibilité',
                'verbose_name_plural': 'Créneaux de disponibilité',
                'ordering': ['jour', 'heure_ouverture'],
                'constraints': [models.UniqueConstraint(fields=('local_entrepot', 'jour'), name='uniq_creneau_local_jour')],
            },
        ),
    ]
