# Generated by Django 5.2.12 on 2026-07-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0017_creneau_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='localentrepot',
            name='statut',
            field=models.BooleanField(default=True, help_text='Coché = Ouvert, décoché = Fermé', verbose_name='Statut'),
        ),
    ]
