# Generated by Django 5.0.3 on 2025-06-29 13:05

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpiece',
            old_name='type_voiture',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='type_voiture',
            new_name='categorie',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='type_voiture',
        ),
        migrations.RemoveField(
            model_name='historicalcategorie',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='historicalcategorie',
            name='type_voiture',
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie',
            field=models.CharField(default='1', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', editable=False, length=6, max_length=6, prefix='', unique=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, default='favicon.ico', null=True, upload_to='robes'),
        ),
        migrations.AddField(
            model_name='historicalcategorie',
            name='categorie',
            field=models.CharField(db_index=True, default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcategorie',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', db_index=True, editable=False, length=6, max_length=6, prefix=''),
        ),
        migrations.AddField(
            model_name='historicalcategorie',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategorie',
            name='image',
            field=models.TextField(blank=True, default='favicon.ico', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpiece',
            name='numero_piece',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='piece',
            name='numero_piece',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
