# Generated by Django 5.2.12 on 2026-09-23 16:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_categorie_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureFNE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'Certification en cours'), ('certifiee', 'Certifiée'), ('echec', 'Échec')], default='en_cours', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, default='', help_text='Numéro de facture attribué par la FNE.', max_length=64)),
                ('fne_invoice_id', models.CharField(blank=True, default='', help_text='Identifiant FNE de la facture, requis pour émettre un avoir.', max_length=64)),
                ('ncc', models.CharField(blank=True, default='', max_length=32)),
                ('url_verification', models.TextField(blank=True, default='', help_text='Lien de vérification DGI, imprimé en QR code sur le reçu.')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timbre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('etablissement', models.CharField(blank=True, default='', max_length=150)),
                ('point_de_vente', models.CharField(blank=True, default='', max_length=150)),
                ('environnement', models.CharField(blank=True, default='', max_length=20)),
                ('alerte_sticker', models.BooleanField(default=False)),
                ('solde_sticker', models.IntegerField(blank=True, null=True)),
                ('date_certification', models.DateTimeField(blank=True, null=True)),
                ('tentatives', models.PositiveIntegerField(default=0)),
                ('erreur', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture_fne', to='stock.commande')),
            ],
            options={
                'verbose_name': 'Facture FNE',
                'verbose_name_plural': 'Factures FNE',
                'ordering': ['-date_creation'],
            },
        ),
    ]
