# Generated by Django 5.0.3 on 2025-06-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_type_voiture_historicalpiece_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrepiece',
            old_name='date_entree',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='historicalentrepiece',
            old_name='date_entree',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='historicalpiece',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='historicalpiece',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='quantite',
        ),
        migrations.AddField(
            model_name='historicalpiece',
            name='quantite_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='quantite_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcategorie',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
