# Generated by Django 5.0.3 on 2025-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_date_entree_entrepiece_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='fichier_pdf',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
