# Generated by Django 5.2.12 on 2026-09-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_facturefne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remise appliquée à la validation panier (Accueil). Plafonnée par CustomUser.plafond_remise et LocalEntrepot.plafond_remise.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalcommande',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remise appliquée à la validation panier (Accueil). Plafonnée par CustomUser.plafond_remise et LocalEntrepot.plafond_remise.', max_digits=10),
        ),
    ]
