# Generated by Django 5.0.3 on 2025-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_commande_utilisateur_alter_panier_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpanier',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
