# Generated by Django 5.0.3 on 2025-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_historicalpanier_date_livraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpanier',
            name='date_livraison',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='date_livraison',
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='date_livr_panier',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='date_paie_panier',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='date_livr_panier',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='date_paie_panier',
            field=models.DateField(blank=True, null=True),
        ),
    ]
