# Generated by Django 5.0.3 on 2025-11-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_historicalpanier_date_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, default='favicon.ico', null=True, upload_to='vehicules'),
        ),
    ]
