# Generated by Django 5.0.3 on 2025-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_moyenpaiement_commande_moyen_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpiece',
            name='active_sortie',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='active_sortie',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
