# Generated by Django 5.0.3 on 2025-12-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_historicalpiece_active_sortie_piece_active_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
