# Generated by Django 5.0.3 on 2025-12-15 15:24

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_commande_date_historicalcommande_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False, unique=True)),
                ('type_notification', models.CharField(choices=[('stock_alerte', 'Alerte de Stock'), ('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès')], default='stock_alerte', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pieces_alerte', models.ManyToManyField(blank=True, related_name='notifications_alerte', to='stock.piece')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
