# Generated by Django 5.0.3 on 2025-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpanier',
            name='proforma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='panier',
            name='proforma',
            field=models.BooleanField(default=False),
        ),
    ]
