# Generated by Django 5.0.3 on 2025-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_historicalpanier_proforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpanier',
            name='nom_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='nom_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
