# Generated by Django 5.2.12 on 2026-03-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0009_rename_siteuser_localentrepot_and_more'),
        ('stock', '0015_add_statut_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpiece',
            name='local_entrepot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.localentrepot'),
        ),
        migrations.AddField(
            model_name='piece',
            name='local_entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_entrepot_pieces', to='Userauths.localentrepot'),
        ),
    ]
