# Generated by Django 5.2.12 on 2026-04-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0009_rename_siteuser_localentrepot_and_more'),
        ('stock', '0016_historicalpiece_local_entrepot_piece_local_entrepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpanier',
            name='local_entrepot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.localentrepot'),
        ),
        migrations.AddField(
            model_name='panier',
            name='local_entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='Userauths.localentrepot'),
        ),
    ]
