# Generated by Django 5.2.12 on 2026-05-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_piece_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpiece',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
