# Generated by Django 5.2.12 on 2026-05-21 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0010_alter_customuser_role_gestionnaire'),
        ('stock', '0024_remove_piece_legacy_stock_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stocklocal',
            new_name='stock_stock_piece_i_87bb66_idx',
            old_name='stock_stock_piece_i_idx',
        ),
        migrations.AlterField(
            model_name='entrepiece',
            name='local_entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrees_stock', to='Userauths.localentrepot'),
        ),
        migrations.AlterField(
            model_name='historicalpiece',
            name='emplacement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalpiece',
            name='seuil',
            field=models.PositiveIntegerField(default=0, help_text='Seuil catalogue (défaut si seuil local non défini)'),
        ),
    ]
