# Generated by Django 6.0.3 on 2026-05-22 16:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0011_alter_customuser_role_chefagence'),
        ('stock', '0026_permission_menu_transferts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepiece',
            name='origine_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_provenance_transfert', to='Userauths.localentrepot'),
        ),
        migrations.AddField(
            model_name='entrepiece',
            name='origine_type',
            field=models.CharField(choices=[('fournisseur', 'Fournisseur'), ('transfert_local', 'Transfert inter-localité')], default='fournisseur', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalentrepiece',
            name='origine_local',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.localentrepot'),
        ),
        migrations.AddField(
            model_name='historicalentrepiece',
            name='origine_type',
            field=models.CharField(choices=[('fournisseur', 'Fournisseur'), ('transfert_local', 'Transfert inter-localité')], default='fournisseur', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('stock_alerte', 'Alerte de Stock'), ('transfert_demande', 'Demande de transfert'), ('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès')], default='stock_alerte', max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=30, unique=True)),
                ('motif', models.TextField(blank=True)),
                ('numero_bon_commande', models.CharField(blank=True, help_text='Numéro saisi par le demandeur à la réception (doit correspondre au bon donneur).', max_length=100)),
                ('numero_bon_donneur', models.CharField(blank=True, help_text="Numéro de bon saisi par le chef d'agence donneur à la validation.", max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('recue', 'Reçue'), ('annulee_demandeur', 'Annulée (demandeur)'), ('annulee_donneur', 'Annulée (donneur)')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert_creees', to=settings.AUTH_USER_MODEL)),
                ('local_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_emises', to='Userauths.localentrepot')),
                ('local_donneur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_recues', to='Userauths.localentrepot')),
                ('receveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert_recues_user', to=settings.AUTH_USER_MODEL)),
                ('validateur_donneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.AddField(
            model_name='entrepiece',
            name='demande_transfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_stock', to='stock.demandetransfert'),
        ),
        migrations.AddField(
            model_name='historicalentrepiece',
            name='demande_transfert',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.demandetransfert'),
        ),
        migrations.CreateModel(
            name='HistoricalDemandeTransfert',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_demande', models.CharField(db_index=True, max_length=30)),
                ('motif', models.TextField(blank=True)),
                ('numero_bon_commande', models.CharField(blank=True, help_text='Numéro saisi par le demandeur à la réception (doit correspondre au bon donneur).', max_length=100)),
                ('numero_bon_donneur', models.CharField(blank=True, help_text="Numéro de bon saisi par le chef d'agence donneur à la validation.", max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('recue', 'Reçue'), ('annulee_demandeur', 'Annulée (demandeur)'), ('annulee_donneur', 'Annulée (donneur)')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(blank=True, editable=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('demandeur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('local_demandeur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.localentrepot')),
                ('local_donneur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.localentrepot')),
                ('receveur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validateur_donneur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical demande transfert',
                'verbose_name_plural': 'historical demande transferts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLigneDemandeTransfert',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('demande', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.demandetransfert')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.piece')),
            ],
            options={
                'verbose_name': 'historical ligne demande transfert',
                'verbose_name_plural': 'historical ligne demande transferts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LigneDemandeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.demandetransfert')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_demande_transfert', to='stock.piece')),
            ],
        ),
        migrations.AddConstraint(
            model_name='demandetransfert',
            constraint=models.CheckConstraint(condition=models.Q(('local_demandeur', models.F('local_donneur')), _negated=True), name='demande_transfert_demandeur_diff_donneur'),
        ),
        migrations.AddConstraint(
            model_name='lignedemandetransfert',
            constraint=models.UniqueConstraint(fields=('demande', 'piece'), name='demande_transfert_ligne_piece_unique'),
        ),
    ]
