# Generated by Django 6.0.3 on 2026-05-23 00:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0011_alter_customuser_role_chefagence'),
        ('stock', '0028_permission_transferts_chefagence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommandePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=30, unique=True)),
                ('ticket_numero', models.CharField(max_length=100)),
                ('client_nom', models.CharField(blank=True, max_length=255)),
                ('moyen_paiement_nom', models.CharField(blank=True, max_length=100)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_reste', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_commande', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='bons_vente/')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_caisse_emis', to=settings.AUTH_USER_MODEL)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_paiement', to='stock.commande')),
                ('hote_accueil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_hote_accueil', to=settings.AUTH_USER_MODEL)),
                ('local_entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_paiement', to='Userauths.localentrepot')),
            ],
            options={
                'verbose_name': 'Bon de commande (paiement)',
                'verbose_name_plural': 'Bons de commande (paiement)',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBonCommandePaiement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_bon', models.CharField(db_index=True, max_length=30)),
                ('ticket_numero', models.CharField(max_length=100)),
                ('client_nom', models.CharField(blank=True, max_length=255)),
                ('moyen_paiement_nom', models.CharField(blank=True, max_length=100)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_reste', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_commande', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fichier_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('date_emission', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('caissier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.commande')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hote_accueil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('local_entrepot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.localentrepot')),
            ],
            options={
                'verbose_name': 'historical Bon de commande (paiement)',
                'verbose_name_plural': 'historical Bons de commande (paiement)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
