# Generated by Django 6.0.3 on 2026-05-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_bon_commande_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstocklocal',
            name='prix_unitaire_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente fixé par la localité. Si vide, utilise le prix catalogue.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocklocal',
            name='prix_unitaire_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente fixé par la localité. Si vide, utilise le prix catalogue.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpiece',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix catalogue / référence (gestionnaire). Les localités peuvent définir un prix sur StockLocal.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix catalogue / référence (gestionnaire). Les localités peuvent définir un prix sur StockLocal.', max_digits=10),
        ),
    ]
