# Generated by Django 6.0.3 on 2026-05-23 22:08

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_stocklocal_prix_unitaire_local'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeTimbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour la dernière tranche (« et plus »).', max_digits=12, null=True)),
                ('montant_timbre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Barème de timbre',
                'verbose_name_plural': 'Barèmes de timbres',
                'ordering': ['montant_min'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_timbre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Timbre fiscal (espèces). Non inclus dans le CA (Commande.total).', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='montant_timbre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Timbre fiscal (espèces). Non inclus dans le CA (Commande.total).', max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='bareme_timbre',
            field=models.ForeignKey(blank=True, help_text='Barème appliqué au moment du paiement.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.baremetimbre'),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='bareme_timbre',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Barème appliqué au moment du paiement.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.baremetimbre'),
        ),
        migrations.CreateModel(
            name='HistoricalBaremeTimbre',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('montant_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour la dernière tranche (« et plus »).', max_digits=12, null=True)),
                ('montant_timbre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Barème de timbre',
                'verbose_name_plural': 'historical Barèmes de timbres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _seed_baremes_timbre(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _seed_baremes_timbre(apps):
    BaremeTimbre = apps.get_model('stock', 'BaremeTimbre')
    if BaremeTimbre.objects.exists():
        return
    tranches = [
        (5001, 100000, 100),
        (100001, 500000, 500),
        (500001, 1000000, 1000),
        (1000001, 5000000, 2000),
        (5000001, None, 5000),
    ]
    for montant_min, montant_max, montant_timbre in tranches:
        BaremeTimbre.objects.create(
            montant_min=montant_min,
            montant_max=montant_max,
            montant_timbre=montant_timbre,
            actif=True,
        )
