# Generated by Django 5.2.12 on 2026-05-23 22:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_timbre_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baremetimbre',
            name='montant_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour la tranche « et plus ».', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='bareme_timbre',
            field=models.ForeignKey(blank=True, help_text='Barème appliqué au moment du paiement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='stock.baremetimbre'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_timbre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Timbre fiscal (espèces). Non inclus dans le CA (total).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalbaremetimbre',
            name='montant_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour la tranche « et plus ».', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommande',
            name='montant_timbre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Timbre fiscal (espèces). Non inclus dans le CA (total).', max_digits=10),
        ),
    ]
