# Generated by Django 6.0.3 on 2026-05-25 22:37

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_archive_motif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpiece',
            name='active_sortie',
            field=models.BooleanField(default=True, help_text='Archivage catalogue global (toutes localités).', null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='active_sortie',
            field=models.BooleanField(default=True, help_text='Archivage catalogue global (toutes localités).', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalTarifLivraison',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cout_par_km', models.DecimalField(decimal_places=2, help_text="Coût par défaut en FCFA / km (si aucun palier ne s'applique)", max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_effet', models.DateTimeField(blank=True, editable=False)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, help_text='Raison du changement de tarif')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tarif de livraison',
                'verbose_name_plural': 'historical Tarifs de livraison',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TarifLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_par_km', models.DecimalField(decimal_places=2, help_text="Coût par défaut en FCFA / km (si aucun palier ne s'applique)", max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_effet', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, help_text='Raison du changement de tarif')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifs_livraison_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarif de livraison',
                'verbose_name_plural': 'Tarifs de livraison',
                'ordering': ['-date_effet'],
            },
        ),
        migrations.CreateModel(
            name='PalierLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('km_max', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour « et plus »', max_digits=8, null=True)),
                ('cout_par_km', models.DecimalField(decimal_places=2, help_text='Tarif FCFA/km pour cet intervalle', max_digits=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='stock.tariflivraison')),
            ],
            options={
                'verbose_name': 'Palier de livraison',
                'verbose_name_plural': 'Paliers de livraison',
                'ordering': ['ordre', 'km_min'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBonLivraison',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_bon_livraison', models.CharField(db_index=True, max_length=30)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance estimée entre les deux localités', max_digits=8)),
                ('cout_base', models.DecimalField(decimal_places=2, help_text='Coût calculé automatiquement (figé à la création)', max_digits=12)),
                ('cout_ajustement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ajustement manuel (+ surcharge, − remise)', max_digits=12)),
                ('motif_ajustement', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('en_route', 'En route'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_preparation', max_length=20)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('fichier_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('demande_transfert', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.demandetransfert')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, db_constraint=False, help_text='Livreur de la localité donneuse', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarif_applique', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.tariflivraison')),
            ],
            options={
                'verbose_name': 'historical Bon de livraison',
                'verbose_name_plural': 'historical Bons de livraison',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon_livraison', models.CharField(max_length=30, unique=True)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance estimée entre les deux localités', max_digits=8)),
                ('cout_base', models.DecimalField(decimal_places=2, help_text='Coût calculé automatiquement (figé à la création)', max_digits=12)),
                ('cout_ajustement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ajustement manuel (+ surcharge, − remise)', max_digits=12)),
                ('motif_ajustement', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('en_route', 'En route'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_preparation', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='bons_livraison/')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_livraison_crees', to=settings.AUTH_USER_MODEL)),
                ('demande_transfert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison', to='stock.demandetransfert')),
                ('livreur', models.ForeignKey(help_text='Livreur de la localité donneuse', on_delete=django.db.models.deletion.PROTECT, related_name='livraisons_transferts', to=settings.AUTH_USER_MODEL)),
                ('tarif_applique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='stock.tariflivraison')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'ordering': ['-date_creation'],
            },
        ),
    ]
