# Generated by Django 6.0.3 on 2026-06-02 12:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_entreprise_stock(apps, schema_editor):
    LocalEntrepot = apps.get_model('Userauths', 'LocalEntrepot')
    Panier = apps.get_model('stock', 'Panier')
    Piece = apps.get_model('stock', 'Piece')
    StockLocal = apps.get_model('stock', 'StockLocal')
    EntrePiece = apps.get_model('stock', 'EntrePiece')
    Commande = apps.get_model('stock', 'Commande')
    BonCommandePaiement = apps.get_model('stock', 'BonCommandePaiement')

    local_to_ent = {loc.pk: loc.entreprise_id for loc in LocalEntrepot.objects.all()}

    for panier in Panier.objects.filter(entreprise__isnull=True):
        if panier.local_entrepot_id:
            panier.entreprise_id = local_to_ent.get(panier.local_entrepot_id)
        elif panier.utilisateur_id and getattr(panier.utilisateur, 'entreprise_id', None):
            panier.entreprise_id = panier.utilisateur.entreprise_id
        panier.save(update_fields=['entreprise'])

    for piece in Piece.objects.filter(entreprise__isnull=True):
        if piece.utilisateur_id and getattr(piece.utilisateur, 'entreprise_id', None):
            piece.entreprise_id = piece.utilisateur.entreprise_id
            piece.save(update_fields=['entreprise'])

    for stock in StockLocal.objects.filter(entreprise__isnull=True):
        stock.entreprise_id = local_to_ent.get(stock.local_entrepot_id)
        stock.save(update_fields=['entreprise'])

    for entree in EntrePiece.objects.filter(entreprise__isnull=True):
        entree.entreprise_id = local_to_ent.get(entree.local_entrepot_id)
        entree.save(update_fields=['entreprise'])

    for cmd in Commande.objects.filter(entreprise__isnull=True):
        if cmd.panier_id:
            cmd.entreprise_id = getattr(cmd.panier, 'entreprise_id', None)
            cmd.save(update_fields=['entreprise'])

    for bon in BonCommandePaiement.objects.filter(entreprise__isnull=True):
        if bon.commande_id:
            bon.entreprise_id = getattr(bon.commande, 'entreprise_id', None)
            bon.save(update_fields=['entreprise'])


class Migration(migrations.Migration):

    dependencies = [
        ('Userauths', '0014_entreprise_plan_alter_customuser_role_and_more'),
        ('stock', '0038_parametre_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommandepaiement',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_paiement', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='commande',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='entrepiece',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_stock', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalboncommandepaiement',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalentrepiece',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalparametretva',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalpiece',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='historicalstocklocal',
            name='entreprise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='panier',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='parametretva',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres_tva', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='piece',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='Userauths.entreprise'),
        ),
        migrations.AddField(
            model_name='stocklocal',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='Userauths.entreprise'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='statut',
            field=models.CharField(choices=[('en_preparation', 'En attente'), ('en_route', 'En route'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_preparation', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='statut',
            field=models.CharField(choices=[('en_preparation', 'En attente'), ('en_route', 'En route'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_preparation', max_length=20),
        ),
        migrations.RunPython(backfill_entreprise_stock, migrations.RunPython.noop),
    ]
