# Generated by Django 5.2.12 on 2026-07-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_boncommandepaiement_entreprise_commande_entreprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommandepaiement',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='entrepiece',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalboncommandepaiement',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalcommande',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalentrepiece',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalpanier',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalparametretva',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalpiece',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalstocklocal',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='parametretva',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='stocklocal',
            name='entreprise',
        ),
    ]
