# Generated by Django 6.0.3 on 2026-07-08 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_remove_entreprise_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_confirme_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='commande_en_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_reception_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_livraison_online', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='client_confirme_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='commande_en_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='date_reception_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='livreur',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='commande_en_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='mode_reception',
            field=models.CharField(blank=True, choices=[('livraison', 'Livraison'), ('retrait', 'Retrait en magasin')], default='livraison', max_length=20),
        ),
        migrations.AddField(
            model_name='panier',
            name='commande_en_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panier',
            name='mode_reception',
            field=models.CharField(blank=True, choices=[('livraison', 'Livraison'), ('retrait', 'Retrait en magasin')], default='livraison', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('stock_alerte', 'Alerte de Stock'), ('transfert_demande', 'Demande de transfert'), ('commande_en_ligne', 'Commande en ligne'), ('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès')], default='stock_alerte', max_length=20),
        ),
    ]
