# Generated by Django 5.2.12 on 2026-07-15 14:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_zones_livraison_panier_adresse'),
        ('stock', '0041_commande_en_ligne_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpanier',
            name='adresse_domicile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='instruction_livraison',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='livraison_commune',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ecom.communelivraison'),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='livraison_pays',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ecom.payslivraison'),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='livraison_ville',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ecom.villelivraison'),
        ),
        migrations.AddField(
            model_name='historicalpanier',
            name='telephone_livraison',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='adresse_domicile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='panier',
            name='instruction_livraison',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='livraison_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='ecom.communelivraison'),
        ),
        migrations.AddField(
            model_name='panier',
            name='livraison_pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='ecom.payslivraison'),
        ),
        migrations.AddField(
            model_name='panier',
            name='livraison_ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers', to='ecom.villelivraison'),
        ),
        migrations.AddField(
            model_name='panier',
            name='telephone_livraison',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
