# Generated by Django 6.0.3 on 2026-08-22 16:17

import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def seed_sous_categorie_permissions(apps, schema_editor):
    TypeCustomPermission = apps.get_model('Userauths', 'TypeCustomPermission')
    CustomPermission = apps.get_model('Userauths', 'CustomPermission')
    stocks, _ = TypeCustomPermission.objects.get_or_create(
        categorie='Stocks',
        defaults={'categorie': 'Stocks'},
    )
    perms = [
        ('add_sous_categorie', 'Sous-catégories'),
        ('update_sous_categorie', 'Modifier sous-catégorie'),
        ('delete_sous_categorie', 'Supprimer sous-catégorie'),
    ]
    created = []
    for url, name in perms:
        perm, _ = CustomPermission.objects.get_or_create(
            url=url,
            defaults={'name': name, 'categorie': stocks},
        )
        created.append(perm)
    source = CustomPermission.objects.filter(url='add_categorie').first()
    if not source:
        return
    user_ids = list(source.users.values_list('pk', flat=True))
    if not user_ids:
        return
    for perm in created:
        perm.users.add(*user_ids)


def unseed_sous_categorie_permissions(apps, schema_editor):
    CustomPermission = apps.get_model('Userauths', 'CustomPermission')
    CustomPermission.objects.filter(url__in=[
        'add_sous_categorie',
        'update_sous_categorie',
        'delete_sous_categorie',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_geniuspay_paiement'),
        ('Userauths', '0019_pwd_forget_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSousCategorie',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', db_index=True, editable=False, length=6, max_length=6, prefix='')),
                ('nom', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categorie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.categorie')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sous-catégorie',
                'verbose_name_plural': 'historical Sous-catégories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', editable=False, length=6, max_length=6, prefix='', unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sous_categories')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='stock.categorie')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='historicalpiece',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Sous-catégorie optionnelle, rattachée à la catégorie.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.souscategorie'),
        ),
        migrations.AddField(
            model_name='piece',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, help_text='Sous-catégorie optionnelle, rattachée à la catégorie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='stock.souscategorie'),
        ),
        migrations.AddConstraint(
            model_name='souscategorie',
            constraint=models.UniqueConstraint(fields=('categorie', 'nom'), name='souscategorie_categorie_nom_unique'),
        ),
        migrations.RunPython(
            seed_sous_categorie_permissions,
            unseed_sous_categorie_permissions,
        ),
    ]
