# Generated by Django 6.0.3 on 2026-07-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0041_commande_en_ligne_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_utilisateurs', to='stock.piece')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_pieces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori client',
                'verbose_name_plural': 'Favoris clients',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'piece')},
            },
        ),
    ]
