# Generated by Django 5.2.12 on 2026-08-28 13:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Commune de livraison',
                'verbose_name_plural': 'Communes de livraison',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FavoriPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favori client',
                'verbose_name_plural': 'Favoris clients',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAbonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('accepte_offres', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='PaysLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Ex: CI', max_length=10, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pays de livraison',
                'verbose_name_plural': 'Pays de livraison',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RecherchePopulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(db_index=True, max_length=150, unique=True)),
                ('terme_affiche', models.CharField(max_length=150)),
                ('compteur', models.PositiveIntegerField(default=1)),
                ('derniere_recherche', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recherche populaire',
                'verbose_name_plural': 'Recherches populaires',
                'ordering': ['-compteur', '-derniere_recherche'],
            },
        ),
        migrations.CreateModel(
            name='RechercheRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('terme', models.CharField(db_index=True, max_length=150)),
                ('terme_affiche', models.CharField(max_length=150)),
                ('date_recherche', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recherche récente',
                'verbose_name_plural': 'Recherches récentes',
                'ordering': ['-date_recherche'],
            },
        ),
        migrations.CreateModel(
            name='VilleLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coût de livraison pour cette ville (FCFA).', max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ville de livraison',
                'verbose_name_plural': 'Villes de livraison',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VueRecentePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vue récente',
                'verbose_name_plural': 'Vues récentes',
                'ordering': ['-date_vue'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Active'), ('refused', 'Refusée'), ('closed', 'Fermée')], db_index=True, default='pending', max_length=20)),
                ('handler_mode', models.CharField(choices=[('staff', 'Conseiller'), ('ai', 'IA')], default='staff', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations_client', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation chat',
                'verbose_name_plural': 'Conversations chat',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('system', 'Système'), ('bot', 'Bot')], max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ecom.chatconversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message chat',
                'verbose_name_plural': 'Messages chat',
                'ordering': ['created_at'],
            },
        ),
    ]
