# Generated by Django 5.2.12 on 2026-08-28 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecom', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoripiece',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_utilisateurs', to='stock.piece'),
        ),
        migrations.AddField(
            model_name='favoripiece',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_pieces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rechercherecente',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recherches_recentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='villelivraison',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='ecom.payslivraison'),
        ),
        migrations.AddField(
            model_name='communelivraison',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='ecom.villelivraison'),
        ),
        migrations.AddField(
            model_name='vuerecentepiece',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues_recentes_utilisateurs', to='stock.piece'),
        ),
        migrations.AddField(
            model_name='vuerecentepiece',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues_recentes_pieces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['status', '-last_message_at'], name='ecom_chatco_status_b5042c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['session_key', 'status'], name='ecom_chatco_session_981401_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['client', 'status'], name='ecom_chatco_client__9845de_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ecom_chatme_convers_06dd8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoripiece',
            unique_together={('utilisateur', 'piece')},
        ),
        migrations.AddIndex(
            model_name='rechercherecente',
            index=models.Index(fields=['utilisateur', '-date_recherche'], name='ecom_recher_utilisa_d992bb_idx'),
        ),
        migrations.AddIndex(
            model_name='rechercherecente',
            index=models.Index(fields=['session_key', '-date_recherche'], name='ecom_recher_session_40fe3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rechercherecente',
            constraint=models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', False)), fields=('utilisateur', 'terme'), name='uniq_recherche_recente_user_terme'),
        ),
        migrations.AddConstraint(
            model_name='rechercherecente',
            constraint=models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', True)), fields=('session_key', 'terme'), name='uniq_recherche_recente_session_terme'),
        ),
        migrations.AlterUniqueTogether(
            name='villelivraison',
            unique_together={('pays', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='communelivraison',
            unique_together={('ville', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='vuerecentepiece',
            unique_together={('utilisateur', 'piece')},
        ),
    ]
