# Generated by Django 5.2.12 on 2026-07-09 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
        ('stock', '0041_commande_en_ligne_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VueRecentePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues_recentes_utilisateurs', to='stock.piece')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues_recentes_pieces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue récente',
                'verbose_name_plural': 'Vues récentes',
                'ordering': ['-date_vue'],
                'unique_together': {('utilisateur', 'piece')},
            },
        ),
    ]
