# Generated by Django 6.0.3 on 2026-07-12 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_newsletter_abonne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecherchePopulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(db_index=True, max_length=150, unique=True)),
                ('terme_affiche', models.CharField(max_length=150)),
                ('compteur', models.PositiveIntegerField(default=1)),
                ('derniere_recherche', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recherche populaire',
                'verbose_name_plural': 'Recherches populaires',
                'ordering': ['-compteur', '-derniere_recherche'],
            },
        ),
        migrations.CreateModel(
            name='RechercheRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('terme', models.CharField(db_index=True, max_length=150)),
                ('terme_affiche', models.CharField(max_length=150)),
                ('date_recherche', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recherches_recentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche récente',
                'verbose_name_plural': 'Recherches récentes',
                'ordering': ['-date_recherche'],
                'indexes': [models.Index(fields=['utilisateur', '-date_recherche'], name='ecom_recher_utilisa_d992bb_idx'), models.Index(fields=['session_key', '-date_recherche'], name='ecom_recher_session_40fe3e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', False)), fields=('utilisateur', 'terme'), name='uniq_recherche_recente_user_terme'), models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', True)), fields=('session_key', 'terme'), name='uniq_recherche_recente_session_terme')],
            },
        ),
    ]
