# Generated by Django 5.2.12 on 2026-07-15 14:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_recherche_historique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaysLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Ex: CI', max_length=10, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pays de livraison',
                'verbose_name_plural': 'Pays de livraison',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VilleLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coût de livraison pour cette ville (FCFA).', max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='ecom.payslivraison')),
            ],
            options={
                'verbose_name': 'Ville de livraison',
                'verbose_name_plural': 'Villes de livraison',
                'ordering': ['nom'],
                'unique_together': {('pays', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='CommuneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='ecom.villelivraison')),
            ],
            options={
                'verbose_name': 'Commune de livraison',
                'verbose_name_plural': 'Communes de livraison',
                'ordering': ['nom'],
                'unique_together': {('ville', 'nom')},
            },
        ),
    ]
