from django.urls import path

from .views import (
    about,
    account,
    add_to_cart,
    ajax_cmd_line_detail,
    ajax_livraison_cmd_detail,
    annuler_commande,
    cart,
    cart_clear,
    cart_remove,
    cart_update,
    chat_api_accept,
    chat_api_close,
    chat_api_conversations,
    chat_api_delete,
    chat_api_history_conversations,
    chat_api_messages,
    chat_api_refuse,
    chat_api_typing,
    chat_history,
    chat_inbox,
    chat_thread,
    messages_contact,
    messages_contact_api_delete,
    messages_contact_api_detail,
    messages_contact_api_list,
    messages_contact_api_status,
    checkout,
    checkout_pay,
    cmd_line,
    cmd_line_assigner_livreur,
    cmd_line_valider,
    confirm_order,
    confirmer_reception,
    contact,
    cookies_policy,
    dashboard,
    ajax_set_livraison_zone,
    ajax_communes_livraison,
    ajax_frais_livraison,
    ajax_villes_livraison,
    favori_add,
    favori_remove,
    favori_toggle,
    index,
    imprimer_facture,
    invoice,
    livraison_cmd_livrer,
    LivraisonCmdOnlineView,
    livraison_cmd_payer,
    localite_detail,
    localites_grid,
    mes_commandes,
    newsletter_subscribe,
    page_not_found,
    paiement_echec,
    paiement_succes,
    piece_cart_quantity,
    relancer_paiement_en_ligne,
    privacy_policy,
    search_clear_recent,
    select_local,
    shop,
    shop_detail,
    support,
    terms_condition,
    vues_recentes,
    wishlist,
)

urlpatterns = [
    path('', index, name='ecom_index'),
    path('local/select/', select_local, name='ecom_select_local'),
    # Pages vitrine
    path('boutique/', shop, name='ecom_shop'),
    path('boutique/<int:piece_id>/<slug:slug>/', shop_detail, name='ecom_shop_detail'),
    path('boutique/<int:piece_id>/', shop_detail, name='ecom_shop_detail_legacy'),
    path('recherche/effacer/', search_clear_recent, name='ecom_search_clear'),
    path('a-propos/', about, name='ecom_about'),
    path('contact/', contact, name='ecom_contact'),
    path('support/', support, name='ecom_support'),
    path('localites/', localites_grid, name='ecom_localites'),
    path('localites/<uuid:local_code>/', localite_detail, name='ecom_localite_detail'),
    path('politique-confidentialite/', privacy_policy, name='ecom_privacy_policy'),
    path('politique-cookies/', cookies_policy, name='ecom_cookies_policy'),
    path('conditions-generales/', terms_condition, name='ecom_terms_condition'),
    path('newsletter/', newsletter_subscribe, name='ecom_newsletter'),
    path('compte/', account, name='ecom_account'),
    path('tableau-de-bord/', dashboard, name='ecom_dashboard'),
    path('facture/<str:commande_id>/', invoice, name='ecom_invoice'),
    path('facture/<str:commande_id>/imprimer/', imprimer_facture, name='ecom_imprimer_facture'),
    # Panier & commande
    path('panier/', cart, name='ecom_cart'),
    path('panier/ajouter/<int:piece_id>/', add_to_cart, name='ecom_add_to_cart'),
    path('panier/quantite/<int:piece_id>/', piece_cart_quantity, name='ecom_piece_cart_quantity'),
    path('panier/modifier/<int:item_id>/', cart_update, name='ecom_cart_update'),
    path('panier/retirer/<int:item_id>/', cart_remove, name='ecom_cart_remove'),
    path('panier/vider/', cart_clear, name='ecom_cart_clear'),
    # Favoris client
    path('favoris/', wishlist, name='ecom_wishlist'),
    path('favoris/ajouter/<int:piece_id>/', favori_add, name='ecom_favori_add'),
    path('favoris/retirer/<int:piece_id>/', favori_remove, name='ecom_favori_remove'),
    path('favoris/basculer/<int:piece_id>/', favori_toggle, name='ecom_favori_toggle'),
    # Vues récentes
    path('vus-recemment/', vues_recentes, name='ecom_vues_recentes'),
    path('checkout/', checkout, name='ecom_checkout'),
    path('checkout/paiement/<str:commande_id>/', checkout_pay, name='ecom_checkout_pay'),
    path('ajax/villes-livraison/', ajax_villes_livraison, name='ecom_ajax_villes_livraison'),
    path('ajax/communes-livraison/', ajax_communes_livraison, name='ecom_ajax_communes_livraison'),
    path('ajax/set-livraison/', ajax_set_livraison_zone, name='ecom_ajax_set_livraison'),
    path('ajax/frais-livraison/', ajax_frais_livraison, name='ecom_ajax_frais_livraison'),
    path('commande/valider/', confirm_order, name='ecom_confirm_order'),
    path('paiement/succes/', paiement_succes, name='ecom_paiement_succes'),
    path('paiement/echec/', paiement_echec, name='ecom_paiement_echec'),
    path('commande/<str:commande_id>/payer/', relancer_paiement_en_ligne, name='ecom_payer_commande'),
    path('mes-commandes/', mes_commandes, name='ecom_mes_commandes'),
    path('commande/<str:commande_id>/recu/', confirmer_reception, name='ecom_confirmer_reception'),
    path('commande/<str:commande_id>/annuler/', annuler_commande, name='ecom_annuler_commande'),
    # Chatbot
    path('chat/thread/', chat_thread, name='ecom_chat_thread'),
    path('mag/chat/', chat_inbox, name='ecom_chat_inbox'),
    path('mag/chat/historique/', chat_history, name='ecom_chat_history'),
    path('mag/messages-contact/', messages_contact, name='ecom_messages_contact'),
    path('mag/messages-contact/api/', messages_contact_api_list, name='ecom_messages_contact_api_list'),
    path('mag/messages-contact/api/<int:message_id>/', messages_contact_api_detail, name='ecom_messages_contact_api_detail'),
    path('mag/messages-contact/api/<int:message_id>/status/', messages_contact_api_status, name='ecom_messages_contact_api_status'),
    path('mag/messages-contact/api/<int:message_id>/delete/', messages_contact_api_delete, name='ecom_messages_contact_api_delete'),
    path('mag/chat/api/conversations/', chat_api_conversations, name='ecom_chat_api_conversations'),
    path('mag/chat/api/historique/', chat_api_history_conversations, name='ecom_chat_api_history'),
    path('mag/chat/api/<int:conversation_id>/accept/', chat_api_accept, name='ecom_chat_api_accept'),
    path('mag/chat/api/<int:conversation_id>/refuse/', chat_api_refuse, name='ecom_chat_api_refuse'),
    path('mag/chat/api/<int:conversation_id>/close/', chat_api_close, name='ecom_chat_api_close'),
    path('mag/chat/api/<int:conversation_id>/delete/', chat_api_delete, name='ecom_chat_api_delete'),
    path('mag/chat/api/<int:conversation_id>/messages/', chat_api_messages, name='ecom_chat_api_messages'),
    path('mag/chat/api/<int:conversation_id>/typing/', chat_api_typing, name='ecom_chat_api_typing'),
    # Personnel magasin
    path('mag/commandes-ligne/', cmd_line, name='ecom_cmd_line'),
    path('mag/commandes-ligne/<str:commande_id>/detail/', ajax_cmd_line_detail, name='ecom_cmd_line_detail'),
    path('mag/commandes-ligne/<str:commande_id>/valider/', cmd_line_valider, name='ecom_cmd_line_valider'),
    path('mag/commandes-ligne/<str:commande_id>/assigner/', cmd_line_assigner_livreur, name='ecom_cmd_line_assigner'),
    # Livreur
    path('livraison/en-ligne/', LivraisonCmdOnlineView.as_view(), name='ecom_livraison_cmd_online'),
    path('livraison/en-ligne/<str:commande_id>/detail/', ajax_livraison_cmd_detail, name='ecom_livraison_cmd_detail'),
    path('livraison/en-ligne/<str:commande_id>/payer/', livraison_cmd_payer, name='ecom_livraison_cmd_payer'),
    path('livraison/en-ligne/<str:commande_id>/livrer/', livraison_cmd_livrer, name='ecom_livraison_cmd_livrer'),
]
